### PR TITLE
E2e pkg

### PR DESCRIPTION
**Pull request by enxebre**
Drop e2e tests in favour of using shared pkg

### CODE REVIEW

**Comment by enxebre** [comment]
cc @bison @frobware @ingvagabund

**Comment by ingvagabund** [comment]
`vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/openshift/suites/smoke_suite.go:489:17: unknown field 'UnneededTime' in struct literal of type v1alpha1.ScaleDownConfig`

**Pull request merged**
