### PR TITLE
Bug 1954177: Update mao dependency for webhook v1 changes

### PR DESCRIPTION
**Pull request by elmiko**

### CODE REVIEW

**Comment by elmiko** [comment]
needed by:
https://github.com/openshift/cluster-api-provider-kubevirt/pull/35
https://github.com/openshift/cluster-api-provider-openstack/pull/180
https://github.com/openshift/cluster-api-actuator-pkg/pull/211

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Pull request merged**
