### PR TITLE
OCPCLOUD-2441,OCPBUGS-25565: Merge https://github.com/kubernetes-sigs/cluster-api-provider-aws:v2.4.0 (25a0086) into master

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@damdo Any idea on the test failures? Related? Flakes?

**Comment by damdo** [comment]
Investigating..
/retest

**Comment by damdo** [comment]
@JoelSpeed  With the MCO issue fixed, this is now failing because CAPA 2.4.0 stopped storing and serving the v1beta1 API, which we still use in the cluster-capi-operator. (cc. @vincepri which worked on this upstream).

I was already planning to switch to v1beta2 with [this PR](https://github.com/openshift/cluster-capi-operator/pull/151/files), but with the recent upstream change, it looks like now this PR depends on that one.

Unless we temporarily re-enable serving v1beta1 and merge the two independently.

**Comment by JoelSpeed** [comment]
@damdo How far off is the v1beta2 move PR? Can we get that in this week?

**Comment by damdo** [comment]
Ran this in combination with https://github.com/openshift/cluster-capi-operator/pull/151
```
launch openshift/cluster-capi-operator#151,openshift/cluster-api-provider-aws#499 aws,techpreview
```

AWS CAPI E2Es passed successfully:
```
Cluster API AWS MachineSet should be able to run a machine with a default provider spec
/Users/ddonati/src/cluster-capi-operator/e2e/aws_test.go:62
  STEP: Creating core cluster @ 03/04/24 20:50:37.945
  STEP: Creating AWS cluster @ 03/04/24 20:50:38.617
  STEP: Creating AWS machine template @ 03/04/24 20:50:39.171
  STEP: Creating MachineSet "aws-machineset" @ 03/04/24 20:50:39.366
  STEP: Waiting for MachineSet machines "aws-machineset" to enter Running phase @ 03/04/24 20:50:39.565
  STEP: Deleting MachineSet "aws-machineset" @ 03/04/24 20:55:24.544
  STEP: Waiting for MachineSet "aws-machineset" to be deleted @ 03/04/24 20:55:24.729
  STEP: Deleting /aws-machine-template @ 03/04/24 20:57:29.516
• [412.502 seconds]
------------------------------

Ran 1 of 3 Specs in 413.401 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 2 Skipped
PASS

Ginkgo ran 1 suite in 7m6.607934445s
Test Suite Passed
```

**Comment by damdo** [comment]
/hold
For controlling the merge

**Review by vincepri — APPROVED** [review]
/lgtm

**Pull request merged**
