### PR TITLE
Bug 1803766: Remove glog package in favor of klog

### PR DESCRIPTION
**Pull request by alexander-demichev**
We are using 2 different logging libraries for no reason. This PR removes unnecessary one.

### CODE REVIEW

**Comment by enxebre** [comment]
Thanks!
Needs a bugzilla reference
/retest

**Comment by enxebre** [comment]
/hold
to stop the bot from retesting.
@alexander-demichev the machine controller is not able to run https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-aws/290/pull-ci-openshift-cluster-api-provider-aws-master-e2e-aws/1250/artifacts/e2e-aws/must-gather/registry-svc-ci-openshift-org-ci-op-7cfyrwch-stable-sha256-a273f5ac7f1ad8f7ffab45205ac36c8dff92d9107ef3ae429eeb135fa8057b8b/namespaces/openshift-machine-api/pods/machine-api-controllers-869bfc6b54-xq5lr/machine-controller/machine-controller/logs/current.log

**Comment by enxebre** [comment]
would this affects the underlying libs using glog?

**Comment by alexander-demichev** [comment]
@enxebre Can you please explain it? Other providers don't use `glog`

**Pull request merged**
