### PR TITLE
Update EC2 instance types

### PR DESCRIPTION
**Pull request by yselkowitz**
/cc @Prashanth684﻿

### CODE REVIEW

**Comment by LorbusChris** [comment]
multiple issues affecting the upgrade job today unfortunately:
https://bugzilla.redhat.com/show_bug.cgi?id=1933760
https://bugzilla.redhat.com/show_bug.cgi?id=1925698

I'll give it one more try
/retest

**Comment by yselkowitz** [comment]
sigh
/retest

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-upgrade

This job won't be affected by the changes in this PR, we know the upgrades are failing all over. Should be ok to merge this without it being passed

**Comment by JoelSpeed** [comment]
/retitle Bug 1896321: Update EC2 instance types

**Pull request merged**
