### PR TITLE
[release-4.15] OCPBUGS-31036: UPSTREAM: 4670:Update awsmachine providerID and instanceID immediately after ec2:RunInstances is called

### PR DESCRIPTION
**Pull request by Patryk-Stefanski**
Carrying  [4670](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4670)

### CODE REVIEW

**Comment by damdo** [comment]
@Patryk-Stefanski that we failure is a known problem. I'll put up a patch to fix it

**Comment by damdo** [comment]
@Patryk-Stefanski [this PR](https://github.com/openshift/cluster-api-provider-aws/pull/503) and its release-4.15 backport will need merging for `e2e-aws-capi-techpreview` to become green

**Comment by Patryk-Stefanski** [comment]
> @Patryk-Stefanski [this PR](https://github.com/openshift/cluster-api-provider-aws/pull/503) and its release-4.15 backport will need merging for `e2e-aws-capi-techpreview` to become green

Ack, Will this also need to be backported to 4.14?

**Comment by damdo** [comment]
If you need to backport this PR also there, then yes

**Comment by damdo** [comment]
/retitle [release-4.15] OCPBUGS-31036: UPSTREAM: 4670:Update awsmachine providerID and instanceID immediately after ec2:RunInstances is called

**Review by damdo — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
