### PR TITLE
tf cleanup

### PR DESCRIPTION
**Pull request by trawler**

### CODE REVIEW

**Comment by enxebre** [comment]
unrelated to this PR but can you please check why the e2e is failing
/lgtm

**Comment by ingvagabund** [comment]
> unrelated to this PR but can you please check why the e2e is failing

Looks like the CI has been failing for a while

**Comment by ingvagabund** [comment]
> error creating EC2 instance: InvalidSubnetID.NotFound: The subnet ID 'subnet-0e56b13a64ff8a941' does not exist\n\tstatus code: 400, request id: 132bda77-5052-4b71-bdc5-101433991373" controller=awsMachine machine=test/aws-actuator-testing-machine-pr-53-45

Yeap, we need to switch to filters instead of hardcoding the subnet ID

**Pull request merged**
