### PR TITLE
Logrus to glog

### PR DESCRIPTION
**Pull request by ingvagabund**
Yet keep the `-log-level` option until it's completely removed from the machine-api-operator.

The mao still renders the controller manifest with the `--log-level` flag.

### CODE REVIEW

**Comment by ingvagabund** [comment]
> operator Instantiate the template e2e-aws into the operator namespace and wait for any pods to complete
> could not wait for pod to complete: could not wait for pod completion: could not list pod: pods "e2e-aws" is forbidden: User "system:serviceaccount:ci:ci-operator" cannot list pods in the namespace "ci-op-idwnpbf9": no RBAC policy matche

/test e2e-aws

**Comment by enxebre** [comment]
We’ll need to update the mao to use new flag, then update actuators back to drop the old flag
What's the motivation for glog over Logrus?
In follow up we really want is to cleanup and unify conventions on all log/error messages format regardless the chosen tool

**Comment by ingvagabund** [comment]
> What's the motivation for glog over Logrus?
In follow up we really want is to cleanup and unify conventions on all log/error messages format regardless the chosen tool

The glog is still used by the upstream community. Plus, it allows you to be more granular in logging messages.

**Pull request merged**
