### PR TITLE
Merge https://github.com/kubernetes-sigs/cluster-api-provider-aws:release-2.0 (28bc9b8) into master

### PR DESCRIPTION
**Pull request by damdo**
This PR merges upstream's https://github.com/kubernetes-sigs/cluster-api-provider-aws:release-2.0 (28bc9b8) into `master`.

Check [this comment](https://github.com/openshift/cluster-capi-operator/pull/101#issue-1564195291) for this CAPI provider bump testing status.

### CODE REVIEW

**Comment by damdo** [comment]
For coordination with other CAPI components:

/hold

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold

Have we run any HyperShift based testing to make sure we aren't breaking them?

**Comment by damdo** [comment]
The Hypershift team, which also uses this fork, https://github.com/openshift/release/pull/36736 an hypershift-e2e test to run as an optional presubmit on PRs in this fork.
Since the [hypeshift-e2e](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-aws/456/pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift/1632726804496125952) is now passing we are going ahead and unholding the PR.

/unhold

**Pull request merged**
