### PR TITLE
Update vendored cluster-api-actuator-pkg with `make check-pkg`

### PR DESCRIPTION
**Pull request by vikaschoudhary16**

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
/test e2e-aws-upgrade
--

**Comment by ingvagabund** [comment]
@vikaschoudhary16 what's intention of this PR? Not sure about what `Update changes from 'make check-pkg'` means. Can't you just run `dep ensure` and create a single commit with all the changes?

**Comment by vikaschoudhary16** [comment]
@ingvagabund Since `make check-pkg` runs `dep ensure` only eventually, so no difference logically in `make check-pkg` or `dep ensure`. May be PR description line is confusing you. Updating it to make it clearer. Thanks!

**Pull request closed without merging**
