### PR TITLE
Lint YAML

### PR DESCRIPTION
**Pull request by paulfantom**
Make YAML linter happy

### CODE REVIEW

**Comment by enxebre** [comment]
thanks! can you include commits for fixes for go-vet and go-lint?

**Comment by paulfantom** [comment]
> can you include commits for fixes for go-vet and go-lint

Depends if you want it done ASAP, or not? :smile:

**Comment by paulfantom** [comment]
Force merging this. More linting will happen after removal of cluster-controller, which will also affect CI config.

**Pull request merged**
