### PR TITLE
OCPBUGS-32114: UPSTREAM: <carry>: Fix instance PrivateDNSName when domain-name is set in dhcpOpts

### PR DESCRIPTION
**Pull request by jparrill**
Initial Bugfix [OCPBUGS-29391](https://issues.redhat.com/browse/OCPBUGS-29391)

When a VPC sets a DHCPOption's domain-name with a custom DNS name, it's being ignored. Now, with this PR, ensure that during instance creation, the controller checks the DHCPOptions and sets the proper PrivateDNSName.

### CODE REVIEW

**Comment by damdo** [comment]
The changes are causing a unit test failure: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-api-provider-aws/508/pull-ci-openshift-cluster-api-provider-aws-release-4.15-unit/1779795681607684096

**Comment by damdo** [comment]
@jparrill this will need a linked bug, happy to use https://issues.redhat.com/browse/OCPBUGS-29391 for it?

**Comment by damdo** [comment]
More context:
This was originally merged in the upstream CAPA release-2.4 branch via: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4921/files

It then got released as upstream CAPA v2.4.2, which got synced up with this downstream CAPA fork on the master/release-4.16 branch.

This is a release-4.15 backport/manual cherry-pick of that fix.

**Comment by jparrill** [comment]
> @jparrill this will need a linked bug, happy to use https://issues.redhat.com/browse/OCPBUGS-29391 for it?

Yes, that works for me

**Comment by damdo** [comment]
/retitle OCPBUGS-29391: UPSTREAM: <carry>: Fix instance PrivateDNSName when domain-name is set in dhcpOpts

**Comment by damdo** [comment]
/retitle OCPBUGS-32114: UPSTREAM: <carry>: Fix instance PrivateDNSName when domain-name is set in dhcpOpts

**Comment by damdo** [comment]
@jparrill I updated the title with the reference to the 4.15 clone bug (OCPBUGS-32114). It looks like the original OCPBUGS-29391 will need to be verified first.

**Pull request merged**
