### PR TITLE
Bug 1949626: update aws-sdk-go to v1.38.25

### PR DESCRIPTION
**Pull request by elmiko**
This change adds support for newer AWS regions which will not be found
with previous client versions.

### CODE REVIEW

**Comment by elmiko** [comment]
i want to investigate a possible alternate solution for this bug. although this change will fix the current issue, there might be a way to change our client to be more accepting of unknown regions.

**Comment by JoelSpeed** [comment]
Even if this isn't the real fix for the problem, it is a valid change and I think we should continue with it anyway

/approve
/retest

**Pull request merged**
