### PR TITLE
bump AWS SDK to v1.35.20

### PR DESCRIPTION
**Pull request by sjenning**
@joelddiaz @michaelgugino 

SDK support for `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` went into v1.21.0

https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v1210-2019-07-18

We are going to need this support for handling full STS mode.  Bumping to the latest v1.35.20 for good measure

### CODE REVIEW

**Review by joelddiaz — COMMENTED** [review]
:+1:

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request merged**
