### PR TITLE
OCPBUGS-2578: Fix go list for go1.18

### PR DESCRIPTION
**Pull request by lobziik**
Specify 'concrete' version of
sigs.k8s.io/cluster-api-provider-{aws|azure}
which makes go to make a correct replace in
`modules.txt` file.

### CODE REVIEW

**Comment by vfreex** [comment]
/lgtm
Tested with go 1.18.6.

**Comment by JoelSpeed** [comment]
Ignition appears to have failed on the proxy test
/retest-required

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-operator

We got most of the way through the suite and failed on the autoscaler tests, I think it's ok to merge this since it's a build related issue, we can see the provider is working

**Pull request merged**
