### PR TITLE
update and run scale down patches

### PR DESCRIPTION
**Pull request by enxebre**
Update and apply the scale down patches

### CODE REVIEW

**Comment by ingvagabund** [comment]
`error: unable to signal to artifacts container to terminate in pod e2e-aws, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")` looks like internal error, not related.
/test e2e-aws

**Comment by ingvagabund** [comment]
`error: unable to check your credentials - pass --skip-check to bypass this error: Get https://registry.svc.ci.openshift.org/v2/: net/http: TLS handshake timeout`
/test e2e-aws

**Comment by wking** [comment]
Cross-linking kubernetes-sigs/cluster-api#513, which seems to be the upstream side of the "Delete specific machine from a machineset when scaling down" patch.  I don't see an upstream commit for "Sort machines before syncing", but maybe it's been squashed in or some such.

**Pull request merged**
