### PR TITLE
Revendor for cluster-api-actuator-pkg

### PR DESCRIPTION
**Pull request by enxebre**
Get https://github.com/openshift/cluster-api-actuator-pkg/pull/63 and https://github.com/openshift/cluster-api-actuator-pkg/pull/61

### CODE REVIEW

**Comment by ingvagabund** [comment]
Interesting:
```
go test -timeout 60m \
	-v ./vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e \
	-kubeconfig ${KUBECONFIG:-~/.kube/config} \
	-machine-api-namespace ${NAMESPACE:-openshift-machine-api} \
	-ginkgo.v \
	-args -v 5 -logtostderr true
# sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go:64:23: undefined: framework.GetWorkerNodes
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go:67:23: undefined: framework.FilterReadyNodes
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go:152:23: undefined: framework.GetWorkerNodes
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go:157:23: undefined: framework.FilterReadyNodes
# sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go:229:23: undefined: framework.GetWorkerNodes
```

**Comment by frobware** [comment]
> Interesting:

I had a go in https://github.com/openshift/cluster-api-provider-aws/pull/197.

**Comment by frobware** [comment]
> I had a go in #197.

Building locally, post the bump, I see: 

```console
$ make test-e2e 
go test -timeout 60m \
	-v ./vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e \
	-kubeconfig ${KUBECONFIG:-~/.kube/config} \
	-machine-api-namespace ${NAMESPACE:-openshift-machine-api} \
	-ginkgo.v \
	-args -v 5 -logtostderr true
=== RUN   TestE2E
Running Suite: Machine Suite
============================
Random Seed: 1555416059
Will run 15 of 15 specs
```

**Comment by enxebre** [comment]
```release "release-latest" failed: the pod ci-op-iymyh6lw/release-latest failed after 38s (failed containers: release): ContainerFailed one or more containers exited

Container release exited with code 1, reason Error
---
info: Using registry public hostname registry.svc.ci.openshift.org
info: Found 138 images in image stream
info: Manifests will be extracted to /tmp/release-image-0.0.1-2019-04-16-120631219838426
error: image "registry.svc.ci.openshift.org/ci-op-iymyh6lw/stable@sha256:5971e043f2f1574f17df7079d5232da975dd684c3df78d2a7794b5b282702362" does not exist
---
```
/retest

**Comment by enxebre** [comment]
```Installing from release registry.svc.ci.openshift.org/ci-op-iymyh6lw/release@sha256:c5fa2bfe72333855dc17c8b38065b2e33c9f46f3268fbd942ef22e813b115e5a
level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating infrastructure resources..."
level=info msg="Waiting up to 30m0s for the Kubernetes API at https://api.ci-op-iymyh6lw-d771b.origin-ci-int-aws.dev.rhcloud.com:6443..."
level=info msg="API v1.13.4+53af542 up"
level=info msg="Waiting up to 30m0s for the bootstrap-complete event..."
level=info msg="Destroying the bootstrap resources..."
level=info msg="Waiting up to 30m0s for the cluster at https://api.ci-op-iymyh6lw-d771b.origin-ci-int-aws.dev.rhcloud.com:6443 to initialize..."
level=fatal msg="failed to initialize the cluster: Cluster operator marketplace is still updating: timed out waiting for the condition"
```

/retest

**Comment by enxebre** [comment]
```
fail [k8s.io/kubernetes/test/e2e/e2e.go:101]: Expected error:
    <*url.Error | 0xc422488090>: {
        Op: "Get",
        URL: "https://api.ci-op-iymyh6lw-d771b.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0",
        Err: {
            Op: "dial",
            Net: "tcp",
            Source: nil,
            Addr: {
                IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 3, 213, 221, 207],
                Port: 6443,
                Zone: "",
            },
            Err: {Syscall: "connect", Err: 0x6f},
        },
    }
    Get https://api.ci-op-iymyh6lw-d771b.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0: dial tcp 3.213.221.207:6443: connect: connection refused
not to have occurred
```
/retest

**Comment by frobware** [comment]
PR #197 did the same thing.

**Pull request closed without merging**
