### PR TITLE
Change apiVersion from awsproviderconfig to aws.cluster.k8s.io.

### PR DESCRIPTION
**Pull request by dgoodwin**
Fixes: https://github.com/openshift/cluster-api-provider-aws/issues/18

### CODE REVIEW

**Comment by dgoodwin** [comment]
CC @ingvagabund

**Comment by ingvagabund** [comment]
@dgoodwin thanks!!!

**Comment by ingvagabund** [comment]
Applied [1] to fix the CI.

[1] https://github.com/openshift/aos-cd-jobs/pull/1562

**Pull request merged**
