### PR TITLE
OCPCLOUD-2703: OWNERS: update subcomponent

### PR DESCRIPTION
**Pull request by damdo**
Update subcomponent, our way of organizing them changed.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@miyadav Any idea why this one is showing the security check as required? Didn't think it should be doing that yet

**Comment by miyadav** [comment]
> @miyadav Any idea why this one is showing the security check as required? Didn't think it should be doing that yet

@JoelSpeed [its](https://github.com/openshift/release/pull/55175/files#diff-0b553a87e6cc958189c6fa14b0397a4929f68e83758ca670ddc25cc028538516) merged hence it is showing that , will have to review  - https://issues.redhat.com/browse/OCPBUGS-38984 to enable merge.

**Comment by damdo** [comment]
/override ci/prow/security

Unrelated to this PR, will need to be looked at anyway though.

**Pull request merged**
