### PR TITLE
OCPCLOUD-2257: Use manifests generation tool from provider repo

### PR DESCRIPTION
**Pull request by damdo**
This PR implements the provider part of the work defined in the [Installing Cluster API components in OpenShift](https://github.com/openshift/enhancements/blob/master/enhancements/cluster-api/installing-cluster-api-components-in-ocp.md) enhancement.

Notably it:
- adds (vendors in) a `manifests-gen` tool hosted as a separate module under the cluster-capi-operator repo
- extends a Make target to invoke the tool
- creates an `openshift/manifests` dir where the generated manifests will be dumped and extends the Dockerfile to load the content of this directory in the payload image accordingly (these manifests will then be deployed by the CVO).

Note:
- After this PR merges, and after https://github.com/openshift/cluster-capi-operator/pull/121 merges, we will need to re-vendor the `manifests-gen` tool.

Manual testing for this combination of PRs ✅  PASSED: see [here](https://github.com/openshift/cluster-api-provider-aws/pull/471#issuecomment-1823024610): 
- openshift/cluster-capi-operator#121
- openshift/cluster-api-provider-aws#471
- openshift/cluster-api#179 (this PR)

### CODE REVIEW

**Comment by damdo** [comment]
/hold
until happy with manual testing

**Comment by damdo** [comment]
Manual e2e testing with a ClusterBot cluster:
`launch openshift/cluster-capi-operator#144,openshift/cluster-api-provider-aws#471,openshift/cluster-api#179 aws,techpreview`

```
[~/src/cluster-capi-operator git:(refactor)] $ oc -n openshift-cluster-api get pods
NAME                                       READY   STATUS    RESTARTS      AGE
capa-controller-manager-59fd59867b-g6twb   1/1     Running   1 (16m ago)   22m
capi-controller-manager-5bbf765989-t27xv   1/1     Running   1 (16m ago)   22m
cluster-capi-operator-b66cc849b-rrq6x      1/1     Running   0             26m

[~/src/cluster-capi-operator git:(refactor)] $ make e2e
./hack/test.sh "./e2e/..." 30m
go run ./hack/../vendor/github.com/onsi/ginkgo/v2/ginkgo -r -v --randomize-all --randomize-suites --keep-going --race --trace --timeout=30m ./e2e/...
Running Suite: Cluster API Suite - /Users/ddonati/src/cluster-capi-operator/e2e
===============================================================================
Random Seed: 1700664807 - will randomize all specs

Will run 3 of 3 specs
------------------------------
[BeforeSuite]
/Users/ddonati/src/cluster-capi-operator/e2e/e2e_test.go:49
[BeforeSuite] PASSED [0.826 seconds]
------------------------------
Cluster API AWS MachineSet should be able to run a machine with a default provider spec
/Users/ddonati/src/cluster-capi-operator/e2e/aws_test.go:62
  STEP: Creating core cluster @ 11/22/23 15:53:39.77
  STEP: Creating AWS cluster @ 11/22/23 15:53:40.366
  STEP: Creating AWS machine template @ 11/22/23 15:53:40.957
  STEP: Creating MachineSet "aws-machineset" @ 11/22/23 15:53:41.162
  STEP: Waiting for MachineSet machines "aws-machineset" to enter Running phase @ 11/22/23 15:53:41.372
  STEP: Comparing instances created by MAPI and CAPI @ 11/22/23 15:58:04.622
  STEP: Deleting MachineSet "aws-machineset" @ 11/22/23 15:58:06.264
  STEP: Waiting for MachineSet "aws-machineset" to be deleted @ 11/22/23 15:58:06.461
  STEP: Deleting /aws-machine-template @ 11/22/23 15:59:09.206
• [330.502 seconds]
------------------------------

Ran 1 of 3 Specs in 331.336 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 2 Skipped
PASS

Ginkgo ran 1 suite in 5m41.98215617s
Test Suite Passed
```

**Comment by enxebre** [comment]
Failing because of https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-aws/471/pull-ci-openshift-cluster-api-provider-aws-master-e2e-hypershift/1727352562639704064
https://github.com/openshift/hypershift/pull/3227

Should go green now
/test e2e-hypershift

**Pull request merged**
