### PR TITLE
Revendor cluster api to drop node controller

### PR DESCRIPTION
**Pull request by enxebre**
originally the logic for setting the nodeRef in a machine was split between the cluster-api node controller and opt-int external tooling that would set an annotation for the former controller to watch. There's no reason for this to keep leaving in two different places, furthermore the cluster-api node controller is deprecated. This PR unifies the current logic and behaviour in one single nodelink controller. See https://github.com/openshift/machine-api-operator/pull/336

### CODE REVIEW

**Comment by enxebre** [comment]
```
7m54s
--
Installing from release registry.svc.ci.openshift.org/ci-op-six05phd/release@sha256:fb8d2f65b77342d070bb7ee907c21380a6d31ab772d822940a2cedae4377ef41 level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised" level=info msg="Consuming \"Install Config\" from target directory" level=info msg="Creating infrastructure resources..." level=error level=error msg="Error: Provider produced inconsistent result after apply" level=error level=error msg="When applying changes to module.vpc.aws_lb_target_group.api_internal, provider" level=error msg="\"aws\" produced an unexpected new value for was present, but now absent." level=error level=error msg="This is a bug in the provider, which should be reported in the provider's own" level=error msg="issue tracker." level=error level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```
/test e2e-aws

**Comment by vikaschoudhary16** [comment]
jenkins/e2e is failing because of older image:  https://github.com/openshift/cluster-api-provider-aws/blob/master/Makefile#L108
e2e-aws-operator is failing because mao image in use is one commit behind the required i.e at https://github.com/openshift/machine-api-operator/commit/00455eaa139fb199b260ff498db35471bc19f55c

e2e-aws failure is  a flake this time.
/test e2e-aws

**Comment by enxebre** [comment]
closing in favour of https://github.com/openshift/cluster-api-provider-aws/pull/233

**Pull request closed without merging**
