### PR TITLE
NO-JIRA: Merge https://github.com/kubernetes-sigs/cluster-api-provider-aws:v2.3.1 (ca3cc2d) into master

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Do we have a particular bug/motivation for bringing this in at this point?

**Comment by damdo** [comment]
Given what Michael said about their patch not being in, non a particular motivation no.

**Comment by damdo** [comment]
Superseded by https://github.com/openshift/cluster-api-provider-aws/pull/499

**Pull request closed without merging**
