### PR TITLE
Bug 1906740: Ensure the region is valid when creating AWS client

### PR DESCRIPTION
**Pull request by JoelSpeed**
This PR ensures that any time we create a client, if the endpoint doesn't resolve to a known standard or custom endpoint, the error returned is an AWS `endpoints.UknownEndpointError` instead of a request error.

Currently, the endpoint resolver falls back to constructing an invalid URL when it doesn't know a particular region, this results in request being made and the error returning looking like `Request Error: Unable to resolve host:...`, now the error will correctly be wrapped such that is says `region "foo" not resolved: Unknown Endpoint: ...` which should hopefully narrow down that the issue is a user input error faster.

This doesn't fully resolve the attached bug but will improve the error message to help towards a resolution.

### CODE REVIEW

**Review by michaelgugino — APPROVED** [review]
/lgtm

This seems sensible to me, probably need to test this thoroughly in QE.

**Review by elmiko — APPROVED** [review]
/approve

**Pull request merged**
