### PR TITLE
Rename AWS credentials secret data keys

### PR DESCRIPTION
**Pull request by spangenberg**

### CODE REVIEW

**Comment by dgoodwin** [comment]
:+1: thanks for doing this, this keeps everyone using cred secrets that I know of in sync so far.

**Comment by ingvagabund** [comment]
@spangenberg can you provide more context? Why is it needed?

**Comment by spangenberg** [comment]
> @spangenberg can you provide more context? Why is it needed?

Sure, the cloud credential operator has a different secret data mapping compared to the one we have.
https://github.com/openshift/cloud-credential-operator/blob/790cd7d7fe0e4ee68b87e7e3531b6c60249f10a1/pkg/controller/secretannotator/secretannotator_controller.go#L64-L65

**Comment by bison** [comment]
/retest

My only concern is whether we need backward comparability, but it's probably not a big deal at this stage.

**Comment by ingvagabund** [comment]
IINM, only our CI was consumer of the AWS secrets. Otherwise, in OpenShift it was aws instance profile that provided means to communicate with AWS service(s).

**Comment by ingvagabund** [comment]
/approve

fine for me though I want another review to confirm/disprove my statement.

**Pull request merged**
