### PR TITLE
Bump openshift/cluster-api dependencies

### PR DESCRIPTION
**Pull request by frobware**
Pickup: https://github.com/openshift/cluster-api/pull/58

### CODE REVIEW

**Comment by frobware** [comment]
e2e tests are currently failing when standing up the cluster:

`Error: Error creating S3 bucket: TooManyBuckets: You have attempted to create more buckets than allowed"`

**Comment by ingvagabund** [comment]
This change is part of https://github.com/openshift/cluster-api-provider-aws/pull/242. Though, if you PR merges first, I will rebase mine.

**Comment by frobware** [comment]
/test e2e-aws-operator

```console
level=error msg="Error: Error creating S3 bucket: TooManyBuckets: You have attempted to create more buckets than allowed"
```

**Pull request merged**
