### PR TITLE
Add termination protection

### PR DESCRIPTION
**Pull request by enxebre**
We want to prevent users from deleting certain special machines.
In the long term we are adding webhook dynamic validation https://jira.coreos.com/browse/CLOUD-297
This is a hack to prevent users from shooting off their foot in the meantime.

Follow up:
If we have consensus on this we'll merge and create the counter part PR in openshift/cluster-api repo to revendor here

### CODE REVIEW

**Comment by enxebre** [comment]
cc @derekwaynecarr @eparis @bison

**Comment by ingvagabund** [comment]
@enxebre can you open the PR in the actuator-pkg repo first? The PR does not introduce any new feature, so it's ok to merge it in actuator-pkg first and then just sync here.

**Pull request closed without merging**
