### PR TITLE
Check if placement is not nil before accessing AvailabilityZone field

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Comment by enxebre** [comment]
placement is not a pointer, I dont think this will panic

**Comment by ingvagabund** [comment]
> placement is not a pointer, I dont think this will panic

Yes, it is. Check `vendor/github.com/aws/aws-sdk-go/service/ec2/api.go:52056`
```
// Describes an instance.
type Instance struct {
	_ struct{} `type:"structure"`
...
	// The location where the instance launched, if applicable.
	Placement *Placement `locationName:"placement" type:"structure"`
...
}
```

**Comment by vikaschoudhary16** [comment]
what does SSIA stand for?

**Pull request merged**
